CREATE TABLE IF NOT EXISTS role (
  role VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS users (
  dni INTEGER NOT NULL ,
  first_name VARCHAR (50) NOT NULL ,
  last_name VARCHAR (50) NOT NULL ,
  genre CHAR (1) ,
  birthday DATE ,
  email VARCHAR(100) NOT NULL ,
  password VARCHAR (100) DEFAULT 'pass',
  role VARCHAR(50) NOT NULL,

  PRIMARY KEY (dni),
  UNIQUE (email),
  CHECK (dni > 0),
  CHECK (birthday <= now() OR birthday IS NULL),
  FOREIGN KEY (role) REFERENCES role ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS address (
  dni INTEGER NOT NULL ,
  country VARCHAR(50) NOT NULL ,
  city VARCHAR(50) NOT NULL ,
  neighborhood VARCHAR(50) NOT NULL ,
  street VARCHAR(100) NOT NULL,
  number INTEGER NOT NULL,
  floor INTEGER,
  door VARCHAR(10),
  telephone INTEGER,
  zip_code INTEGER,

  PRIMARY KEY (dni),
  FOREIGN KEY (dni) REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS student (
  docket SERIAL NOT NULL ,
  dni INTEGER NOT NULL ,

  PRIMARY KEY (docket),
  FOREIGN KEY (dni) REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS admin (
  dni INTEGER NOT NULL,

  PRIMARY KEY (dni),
  FOREIGN KEY (dni) REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS course (
  id INTEGER NOT NULL,
  name VARCHAR(50) NOT NULL,
  credits INTEGER NOT NULL,
  semester INTEGER NOT NULL,

  PRIMARY KEY (id),
  CHECK (id > 0),
  CHECK (credits >= 0),
  CHECK (semester >= 0)
);

CREATE TABLE IF NOT EXISTS inscription (
  docket INTEGER NOT NULL,
  course_id INTEGER NOT NULL,

  PRIMARY KEY (docket, course_id),
  FOREIGN KEY (docket) REFERENCES student ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (course_id) REFERENCES course ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS grade (
  docket INTEGER NOT NULL,
  course_id INTEGER NOT NULL ,
  grade DECIMAL(4,2) NOT NULL ,
  modified TIMESTAMP DEFAULT current_timestamp,

  PRIMARY KEY (docket, course_id, grade, modified),
  FOREIGN KEY (docket) REFERENCES student ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (course_id) REFERENCES course ON DELETE RESTRICT ON UPDATE CASCADE,
  CHECK (grade >= 0)
);

CREATE TABLE IF NOT EXISTS correlative (

  course_id INTEGER NOT NULL ,
  correlative_id INTEGER NOT NULL ,

  PRIMARY KEY (course_id, correlative_id),
  FOREIGN KEY (course_id) REFERENCES course ON UPDATE CASCADE,
  FOREIGN KEY (correlative_id) REFERENCES course ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS authority (
  authority VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS role_authorities (
  role VARCHAR(50) NOT NULL,
  authority VARCHAR(50) NOT NULL,

  PRIMARY KEY (role, authority),
  FOREIGN KEY (role) REFERENCES role ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (authority) REFERENCES authority ON DELETE CASCADE ON UPDATE CASCADE
);