CREATE TABLE IF NOT EXISTS users (
				userid SERIAL PRIMARY KEY,
				username VARCHAR (100),
				password VARCHAR (100)
);

CREATE TABLE IF NOT EXISTS course (
	id INTEGER NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	credits INTEGER NOT NULL
);